# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    open-pull-requests-limit: 20
    schedule:
      interval: "daily"
      time: "04:00"
    groups:
      react:
        applies-to: version-updates
        patterns:
          - "react"
          - "@types/react"
          - "react-dom"
          - "@types/react-dom"
      luxon:
        applies-to: version-updates
        patterns:
          - "luxon"
          - "@types/luxon"
      tailwind:
        applies-to: version-updates
        patterns:
          - "tailwindcss"
          - "eslint-plugin-tailwindcss"
          - "prettier-plugin-tailwindcss"
      typescript-eslint:
        applies-to: version-updates
        patterns:
          - "@typescript-eslint/*"
